const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
 const context=await browser.newContext({viewport:{width:1280,height:900}});
 const page=await context.newPage(), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(/violates.*Content Security Policy/.test(m.text()))errors.push(m.text());});
 await page.goto('http://127.0.0.1:4173');
 await page.locator('#grid a').first().click();await page.locator('#viewProduct').waitFor({state:'visible'});
 await page.getByRole('button',{name:'azul',exact:true}).click();await page.locator('#addToCart').click();
 await page.locator('#backBtn').click();await page.locator('#grid a').nth(2).click();await page.locator('#buyNow').click();
 await page.locator('dialog').waitFor({state:'visible'});
 assert.equal(await page.locator('.shop-line').count(),2);
 assert.match(await page.locator('#cartLines').textContent(),/Capasazul/);
 await page.locator('[name="department"]').selectOption('Bogotá D.C.');assert.match(await page.locator('#cartShipping').textContent(),/20.000/);
 await page.locator('[name="department"]').selectOption('Antioquia');assert.match(await page.locator('#cartShipping').textContent(),/50.000/);
 await page.locator('.shop-controls input').first().fill('2');await page.locator('.shop-controls input').first().dispatchEvent('change');assert.match(await page.locator('#cartShipping').textContent(),/60.000/);
 assert.equal(await page.locator('#checkoutPay').isDisabled(),true);
 assert.equal(await page.getByRole('link',{name:'Prefiero pedir por Instagram ↗'}).getAttribute('href'),'https://www.instagram.com/hogarq_col');
 await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').isVisible(),false);
 await page.reload();await page.locator('#viewProduct [data-open-cart]').click();assert.equal(await page.locator('.shop-line').count(),2);
 await page.keyboard.press('Escape');await page.locator('#backBtn').click();
 // Mock only the public configuration/API for UI testing. No real charges or emails.
 await page.route('**/api/config',route=>route.fulfill({json:{enabled:true,test:true}}));
 await page.reload();await page.locator('#header [data-open-cart]').click();
 await page.locator('[name="department"]').selectOption('Bogotá D.C.');
 for(const [name,value] of Object.entries({name:'Ana de prueba',email:'ana@example.com',phone:'3001234567',address:'Calle 1 # 2-3',neighborhood:'Centro',apartment:'302',instructions:'Portería'}))await page.locator('#checkoutForm [name="'+name+'"]').fill(value);
 await page.locator('[name="consent"]').check();
 let payload;
 await page.route('**/api/checkout',async route=>{payload=route.request().postDataJSON();await route.fulfill({status:503,json:{error:'Prueba: servicio temporalmente no disponible.'}});});
 await page.locator('#checkoutPay').click();await page.locator('#checkoutError').filter({hasText:'Prueba:'}).waitFor();
 assert.equal(payload.customer.city,'Bogotá D.C.');assert.equal(payload.customer.apartment,'302');assert(!('total' in payload));assert(!('price' in payload.items[0]));
 assert.equal(await page.locator('#checkoutPay').isEnabled(),true);
 fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/cart-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/cart-mobile.png'});
 assert.equal(await page.locator('dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);
 const id='bb9c315a-4635-4a64-9f70-eb2882605818';
 await page.evaluate(id=>sessionStorage.setItem('hogarq-order-'+id,JSON.stringify({token:'test-status-token',cart:JSON.parse(localStorage.getItem('hogarq-cart-v1'))})),id);
 await page.route('**/api/order?*',route=>route.fulfill({json:{id,status:'pending',total:310000,delivery:'2–4 días hábiles',test:true,emailAccepted:false}}));
 await page.goto('http://127.0.0.1:4173/?order='+id+'&status=approved#pedido');await page.locator('#statusTitle').filter({hasText:'Pago pendiente'}).waitFor();
 assert.equal(await page.locator('#statusTitle').textContent(),'Prueba · Pago pendiente');
 await page.unroute('**/api/order?*');await page.route('**/api/order?*',route=>route.fulfill({json:{id,status:'approved',total:310000,delivery:'2–4 días hábiles',test:true,emailAccepted:true}}));
 await page.locator('#refreshOrder').click();await page.locator('#statusTitle').filter({hasText:'Pago aprobado'}).waitFor();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hogarq-cart-v1')).length),0);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS browser: catalog, variants, persistent cart, shipping, mobile, Instagram, unavailable checkout, form, pending/approved status.');
})().catch(e=>{console.error(e);process.exit(1);});
